#!/usr/bin/env python
"""
BrainTrace — Master Reproducibility Pipeline
=============================================
End-to-end reproduction of all reported results.

Pipeline phases:
  PRE-BUILD  — Extract nested archives (BraTS NIfTI zip)
  BUILD      — Generate all derived assets from raw data
               1. atlas_database  — braintrace_source_tracing.db (~730 MB)
               2. network_model   — bo2023_saleem_network_top200_model.npz
               3. reference_projector — projected-VSD projector + reference matrices
               4. reference_db    — Streamlit web app SQLite DB
  VALIDATION — Run all validation experiments (LOMO, AHBA, TCGA/BraTS, etc.)
  CSV-GEN    — Regenerate all 10 manuscript CSV files from documented raw counts

Traceability system:
  - DATA_PROVENANCE.md     — Raw data source manifest (accessions, DOIs, SHA256)
  - generate_all_csvs.py   — Dynamic CSV regeneration from raw counts + formulas
  - TRACEABILITY_MATRIX.md — Manuscript number → CSV → formula → raw data mapping

Usage:
    python reproduce_all.py [--verify-only] [--skip-build] [--output-dir DIR]
    python reproduce_all.py --step network_model   # Run a single step

Design principles:
    1. Every input is SHA256-verified before use.
    2. Every random component is pinned to a documented seed.
    3. Every output is checksummed and logged.
    4. The pipeline is idempotent — re-running produces identical results.

Key architectural note:
  The main atlas database (braintrace_source_tracing.db) is a BUILD ARTIFACT
  generated by Step 1 (atlas_database: build_bo2023_atlas_from_wang_matrix.py).
  It is regenerated from the raw data files — it is NOT a pre-existing dependency.
  The pre-built DB is provided as a convenience to skip this expensive step
  via --skip-build.

  The Streamlit reference DB (braintrace_reference_v1.sqlite) is a
  separate, lightweight database built by Step 4 (reference_db).
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import platform
import subprocess
import sys
import time
import zipfile
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

# ── Constants ───────────────────────────────────────────────────────────────

ROOT = Path(__file__).resolve().parent
SHA256SUMS = ROOT / "SHA256SUMS.txt"
REPRO_DIR = ROOT / "reproducibility_audit"
REPRO_DIR.mkdir(parents=True, exist_ok=True)

# Documented seeds — every stochastic operation uses one of these.
# These are identical to the seeds in:
#   scripts/analyze_p0_donor_cluster_inference.py:SEED
#   scripts/generate_p0_hard_evidence.py:RNG_SEED
#   scripts/generate_p2_publication_completeness.py:SEED
#   benchmark_runner.py:random_state=42
#   core/params.py:random_seed=13
SEED_REGISTRY = {
    "donor_cluster_inference": 20260716,  # Manuscript seed for 50,000 donor-cluster bootstrap
    "p0_hard_evidence": 20260629,
    "p2_publication_completeness": 20260629,
    "p0_weighted_random": 20260629,
    "benchmark_stratified_kfold": 42,
    "bootstrap_default": 13,
    "legacy_marker_validation": 20260528,
    "discriminative_correlation": 20260530,
    "correlation_marker_routes": 20260528,
    "sparse_simulation_base": 20260711,  # Base seed; 99,099 archival seeds generated as base + index
    "sparse_simulation_count": 99099,    # Total number of archived unique seeds (not a seed value)
    "rf_fair_comparator": 20260717,
    "per_region_bootstrap": 20260717,    # 418 per-region Top1/Top3 bootstrap records
    "donor_cluster_bootstrap": 20260716, # 50,000 donor-cluster bootstrap resamples
    "sign_flip_test": "exact_2pow9",     # Exhaustive 512 sign patterns (deterministic, no seed)
}

# ── Data structures ──────────────────────────────────────────────────────────


@dataclass
class BuildStep:
    """A single computation step in the pipeline."""

    name: str
    script: Path
    description: str
    produces: list[str]  # relative paths of output files
    depends_on: list[str] = field(default_factory=list)  # relative paths of input files
    extra_args: list[str] = field(default_factory=list)
    seed: str | None = None  # key into SEED_REGISTRY


@dataclass
class AuditRecord:
    """Single audit entry."""

    step: str
    status: str  # "PASS", "FAIL", "SKIP", "WARN"
    duration_sec: float
    output_checksums: dict[str, str] = field(default_factory=dict)
    input_checksums: dict[str, str] = field(default_factory=dict)
    notes: str = ""


@dataclass
class AuditReport:
    generated_at: str
    hostname: str
    platform: str
    python_version: str
    pip_freeze: dict[str, str] = field(default_factory=dict)
    seed_registry: dict[str, int] = field(default_factory=dict)
    raw_data_verification: dict[str, str] = field(default_factory=dict)
    build_steps: list[AuditRecord] = field(default_factory=list)
    validation_steps: list[AuditRecord] = field(default_factory=list)
    final_output_checksums: dict[str, str] = field(default_factory=dict)


# ── Utility functions ────────────────────────────────────────────────────────


def sha256_file(path: Path) -> str:
    """Compute SHA256 hex digest of a file."""
    h = hashlib.sha256()
    with open(path, "rb") as f:
        while True:
            chunk = f.read(65536)
            if not chunk:
                break
            h.update(chunk)
    return h.hexdigest()


def sha256_content(text: str) -> str:
    """Compute SHA256 of a string."""
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def run_step(
    script: Path,
    args: list[str],
    cwd: Path | None = None,
    timeout: int = 3600,
    env: dict | None = None,
) -> tuple[int, str, float]:
    """Run a Python script, capturing stdout/stderr and timing."""
    start = time.perf_counter()
    full_args = [sys.executable, str(script)] + args
    result = subprocess.run(
        full_args,
        cwd=str(cwd or ROOT),
        capture_output=True,
        text=True,
        timeout=timeout,
        env={**os.environ, **(env or {})},
    )
    elapsed = time.perf_counter() - start
    return result.returncode, result.stdout + "\n" + result.stderr, elapsed


# ── Setup helper (pre-build extraction) ─────────────────────────────────────


def extract_brats_nested_zip() -> bool:
    """Extract the nested BraTS-TCGA-LGG NIfTI zip if not already done.

    The BraTS data arrives as a nested package:
      data/brats_tcga_lgg_training_65/
        PKG - BraTS-TCGA-LGG/BraTS-TCGA-LGG/Pre-operative_TCGA_LGG_NIfTI_and_Segmentations.zip

    This step extracts it into:
      data/brats_tcga_lgg_training_65/extracted/
    """
    brats_dir = ROOT / "data" / "brats_tcga_lgg_training_65"
    zip_path = brats_dir / "PKG - BraTS-TCGA-LGG" / "BraTS-TCGA-LGG" / "Pre-operative_TCGA_LGG_NIfTI_and_Segmentations.zip"
    extract_dir = brats_dir / "extracted"

    if not zip_path.exists():
        print(f"  [SKIP] BraTS zip not found at: {zip_path}")
        print(f"  This is expected if running with --skip-build or if data is already extracted.")
        return True  # Not an error — data may already be extracted

    # Check if already extracted (at least 50 patient directories)
    if extract_dir.exists():
        n_dirs = sum(1 for p in extract_dir.iterdir() if p.is_dir())
        if n_dirs >= 50:
            print(f"  [OK] BraTS data already extracted ({n_dirs} patient directories)")
            return True

    # Extract
    print(f"  Extracting {zip_path.name} ({zip_path.stat().st_size / 1e6:.0f} MB)...")
    extract_dir.mkdir(parents=True, exist_ok=True)
    try:
        with zipfile.ZipFile(zip_path, "r") as zf:
            zf.extractall(extract_dir)
        n_dirs = sum(1 for p in extract_dir.iterdir() if p.is_dir())
        print(f"  [OK] Extracted {n_dirs} patient directories")
        return True
    except Exception as e:
        print(f"  [FAIL] Extraction error: {e}")
        return False


# ── Build step definitions ──────────────────────────────────────────────────

BUILD_STEPS: list[BuildStep] = [
    BuildStep(
        name="atlas_database",
        script=ROOT / "scripts" / "build_bo2023_atlas_from_wang_matrix.py",
        description="Build full Bo2023 atlas SQLite database (braintrace_source_tracing.db, ~730 MB). "
                    "This is the single source of truth for all downstream queries. "
                    "Uses the VSD matrix + sample annotation + gene map to populate the schema.",
        produces=["braintrace_source_tracing.db"],
        depends_on=[
            "bo2023 data/mfas5_819samples_23605genes_vsd4_rmbatch.xls",
            "bo2023 data/mfas5_819samples_28415genes_featurecounts_counts.txt",
            "bo2023 data/Information of sequenced samples_update_full878_filter819.xlsx",
            "bo2023_bulk_atlas_buildkit/04_expressed_genes_neocortex_plus_subcortical.csv",
        ],
    ),
    BuildStep(
        name="network_model",
        script=ROOT / "scripts" / "build_bo2023_network_model.py",
        description="Build canonical Bo2023 SaleemNetworks Top200 gene model",
        produces=["data/models/bo2023_saleem_network_top200_model.npz"],
        depends_on=[
            "bo2023 data/mfas5_819samples_23605genes_vsd4_rmbatch.xls",
            "bo2023 data/Information of sequenced samples_update_full878_filter819.xlsx",
        ],
    ),
    BuildStep(
        name="reference_projector",
        script=ROOT / "scripts" / "build_bo2023_reference_projector.py",
        description="Build projected-VSD reference projector (linear, full model)",
        produces=[
            "data/models/bo2023_reference_projector_linear_full.npz",
            "data/models/bo2023_region_logcpm_reference_matrix.npz",
            "data/models/bo2023_formal_region_logcpm_reference_matrix.npz",
        ],
        depends_on=[
            "bo2023 data/mfas5_819samples_23605genes_vsd4_rmbatch.xls",
            "bo2023 data/mfas5_819samples_28415genes_featurecounts_counts.txt",
            "bo2023 data/Information of sequenced samples_update_full878_filter819.xlsx",
            "data/models/bo2023_saleem_network_top200_model.npz",
        ],
    ),
    BuildStep(
        name="reference_db",
        script=ROOT / "scripts" / "build_sqlite_reference_db_v1.py",
        description="Build SQLite reference database for Streamlit web app "
                    "(braintrace_reference_v1.sqlite). "
                    "NOTE: This is the lightweight web-app database, separate from "
                    "the main atlas DB (braintrace_source_tracing.db) built in Step 1.",
        produces=["data/processed_reference/v1/braintrace_reference_v1.sqlite"],
        depends_on=[
            "data/reference_atlases/00_manifest/reference_atlas_manifest.tsv",
            "data/reference_atlases/00_manifest/reference_file_inspection.tsv",
        ],
    ),
]

VALIDATION_STEPS: list[BuildStep] = [
    BuildStep(
        name="lomo_validation",
        script=ROOT / "scripts" / "run_bo2023_lomo_validation.py",
        description="Leave-one-monkey-out formal validation",
        produces=["reports/validation_recheck_20260713_canonical110/lomo/formal_lomo_validation_summary.json"],
        depends_on=[
            "data/models/bo2023_saleem_network_top200_model.npz",
            "data/models/bo2023_formal_region_logcpm_reference_matrix.npz",
        ],
    ),
    BuildStep(
        name="donor_cluster_inference",
        script=ROOT / "scripts" / "analyze_p0_donor_cluster_inference.py",
        description="Donor-clustered LOSO/LOMO inference with bootstrap CIs",
        produces=["reports/validation_recheck_20260713_canonical110/donor_cluster_inference/donor_clustered_loso_lomo_summary.csv"],
        depends_on=[
            "data/models/bo2023_saleem_network_top200_model.npz",
            "data/models/bo2023_formal_region_logcpm_reference_matrix.npz",
        ],
        seed="donor_cluster_inference",
    ),
    BuildStep(
        name="sparse_sensitivity",
        script=ROOT / "scripts" / "run_p0_4_sparse_domain_shift_sensitivity.py",
        description="Sparse-query robustness simulation (5 scenarios × 3 reps)",
        produces=["reports/validation_recheck_20260713_canonical110/sparse_sensitivity/p0_4_sparse_sensitivity_summary.csv"],
        depends_on=[
            "data/models/bo2023_saleem_network_top200_model.npz",
            "data/models/bo2023_formal_region_logcpm_reference_matrix.npz",
        ],
        seed="sparse_simulation_base",
    ),
    BuildStep(
        name="ahba_validation",
        script=ROOT / "scripts" / "run_ahba_projected_vsd_formal_three_tier_external.py",
        description="AHBA external validation with 2-donor projected-VSD",
        produces=["reports/validation_recheck_20260713_canonical110/ahba/ahba_formal_three_tier_resolution_audit.csv"],
        depends_on=[
            "data/models/bo2023_saleem_network_top200_model.npz",
            "data/models/bo2023_formal_region_logcpm_reference_matrix.npz",
            "data/ahba_human_rnaseq/ahba_human_rnaseq_tpm_gene_symbol_matrix.tsv",
        ],
    ),
    BuildStep(
        name="rf_fair_comparator",
        script=ROOT / "validation_runs/r08_rf_fair_comparator_20260717" / "run_rf_comparator.py",
        description="Random Forest fair comparator (300 trees, SelectKBest k=500, LOMO)",
        produces=["validation_runs/r08_rf_fair_comparator_20260717/full_outputs/full_contract.json"],
        depends_on=[
            "data/models/bo2023_saleem_network_top200_model.npz",
            "data/models/bo2023_formal_region_logcpm_reference_matrix.npz",
        ],
        seed="rf_fair_comparator",
    ),
    BuildStep(
        name="tcga_brats_evaluation",
        script=ROOT / "scripts" / "evaluate_brats_tcga_lgg_65_mri_truth.py",
        description="TCGA/BraTS 65-patient MRI truth evaluation",
        produces=["results/archived_tcga_brats/brats_tcga_lgg_65_mri_truth_evaluation_20260609/brats_tcga_lgg_65_mri_truth_and_predictions.csv"],
        depends_on=[
            "data/models/bo2023_saleem_network_top200_model.npz",
            "data/models/bo2023_formal_region_logcpm_reference_matrix.npz",
            "data/brats_tcga_lgg_training_65/",
        ],
    ),
    BuildStep(
        name="p2_completeness",
        script=ROOT / "scripts" / "generate_p2_publication_completeness.py",
        description="Publication completeness package (ML baselines, seed registry, tool comparison)",
        produces=[
            "reports/p2_publication_completeness_20260629/ml_baselines/",
            "reports/p2_publication_completeness_20260629/engineering_reproducibility/random_seed_registry.json",
        ],
        depends_on=[
            "bo2023 data/mfas5_819samples_23605genes_vsd4_rmbatch.xls",
            "bo2023 data/Information of sequenced samples_update_full878_filter819.xlsx",
        ],
        seed="p2_publication_completeness",
    ),
    BuildStep(
        name="loso_validation",
        script=ROOT / "scripts" / "run_bo2023_loso_validation.py",
        description="Leave-one-sample-out formal validation (Network/resolution-group/exact-region Top1/Top3)",
        produces=["reports/validation_recheck_20260713_canonical110/loso/formal_loso_validation_summary.json"],
        depends_on=[
            "data/models/bo2023_saleem_network_top200_model.npz",
            "data/models/bo2023_formal_region_logcpm_reference_matrix.npz",
        ],
    ),
    BuildStep(
        name="gse189919_benchmark",
        script=ROOT / "scripts" / "benchmark_gse189919_engineering.py",
        description="GSE189919 engineering performance benchmark (cold/warm inference timing)",
        produces=["reports/gse189919_benchmark/engineering_benchmark_report.json"],
        depends_on=[
            "data/models/bo2023_saleem_network_top200_model.npz",
            "data/models/bo2023_reference_projector_linear_full.npz",
        ],
    ),
    BuildStep(
        name="huang2025_domain_audit",
        script=ROOT / "scripts" / "audit_huang2025_domain_shift.py",
        description="Huang2025 cfRNA domain-shift audit (159 CSF/plasma profiles)",
        produces=["reports/huang2025_domain_audit/domain_transfer_audit.json"],
        depends_on=[
            "data/models/bo2023_saleem_network_top200_model.npz",
            "data/models/bo2023_reference_projector_linear_full.npz",
            "external_inputs/huang2025_pmc12041490/41698_2025_909_MOESM2_ESM.csv",
        ],
    ),
    BuildStep(
        name="lambda_sensitivity_friedman",
        script=ROOT / "scripts" / "analyze_lambda_sensitivity_friedman.py",
        description="Lambda sensitivity analysis (0.25, 0.50, 0.75) + Friedman chi-squared test",
        produces=["reports/lambda_sensitivity/friedman_test_results.csv"],
        depends_on=[
            "data/models/bo2023_saleem_network_top200_model.npz",
            "data/models/bo2023_formal_region_logcpm_reference_matrix.npz",
        ],
    ),
    BuildStep(
        name="subcortical_subsampling",
        script=ROOT / "scripts" / "analyze_subcortical_ppv_subsampling.py",
        description="Subcortical PPV/recall bootstrap subsampling (9 fractions x 2000 reps)",
        produces=["reports/subcortical_subsampling/subcortical_ppv_recall_stability.csv"],
        depends_on=[
            "data/models/bo2023_saleem_network_top200_model.npz",
            "data/models/bo2023_formal_region_logcpm_reference_matrix.npz",
        ],
    ),
    BuildStep(
        name="loso_lomo_sign_flip",
        script=ROOT / "scripts" / "test_loso_lomo_sign_flip.py",
        description="LOSO-vs-LOMO exact sign-flip test (3 prespecified Top3 comparisons, 2^9=512 patterns, BH-corrected)",
        produces=["reports/sign_flip_test/loso_lomo_sign_flip_results.json"],
        depends_on=[
            "data/models/bo2023_saleem_network_top200_model.npz",
            "data/models/bo2023_formal_region_logcpm_reference_matrix.npz",
        ],
        seed="sign_flip_test",
    ),
    BuildStep(
        name="per_region_bootstrap",
        script=ROOT / "scripts" / "analyze_per_region_bootstrap.py",
        description="Per-region Top1/Top3 bootstrap (418 records, 50,000 donor-block draws, seed 20260717)",
        produces=["reports/per_region_bootstrap/per_region_top1_top3_bootstrap.csv"],
        depends_on=[
            "data/models/bo2023_saleem_network_top200_model.npz",
            "data/models/bo2023_formal_region_logcpm_reference_matrix.npz",
        ],
        seed="per_region_bootstrap",
    ),
    BuildStep(
        name="unit_tests",
        script=ROOT / "tests" / "run_tests.py",
        description="Unit test suite (pytest) - core scoring, hierarchy, validation utilities",
        produces=["reports/unit_tests/pytest_results.xml"],
        depends_on=[],
    ),
    BuildStep(
        name="manuscript_csvs",
        script=ROOT / "reproducibility" / "generate_all_csvs.py",
        description="Regenerate all 10 manuscript supplementary CSV files from documented raw counts. "
                    "Computes Wilson/CP/AC CIs, bootstrap CIs, binomial tests, Friedman tests, "
                    "and macro/weighted F1 summaries from raw validation counts. "
                    "Every number in the manuscript is traceable through: CSV → formula → raw data.",
        produces=[
            "v4_p0_9_triple_ci.csv",
            "v4_p0_4_subcortical_subsampling.csv",
            "v4_p0_5_ahba_trace.csv",
            "v4_p0_5_ahba_trace_manuscript_aligned.csv",
            "v4_p0_10_lambda_friedman.csv",
            "v4_p0_10_lambda_sensitivity.csv",
            "v4_p0_11_ml_baselines.csv",
            "v4_p0_11_rf_comparator.csv",
            "v4_p0_12_tcga_brats_ci_summary.csv",
            "v4_p0_13_macro_f1.csv",
        ],
        depends_on=[],
    ),
]

RAW_DATA_SOURCES = {
    # Primary atlas data (immutable — the foundation of all computation)
    "bo2023_vsd_matrix": "bo2023 data/mfas5_819samples_23605genes_vsd4_rmbatch.xls",
    "bo2023_counts_matrix": "bo2023 data/mfas5_819samples_28415genes_featurecounts_counts.txt",
    "bo2023_sample_info": "bo2023 data/Information of sequenced samples_update_full878_filter819.xlsx",
    "bo2023_gene_map": "bo2023_bulk_atlas_buildkit/04_expressed_genes_neocortex_plus_subcortical.csv",
    # External validation data
    "ahba_tpm_matrix": "data/ahba_human_rnaseq/ahba_human_rnaseq_tpm_gene_symbol_matrix.tsv",
    "ahba_metadata": "data/ahba_human_rnaseq/ahba_human_rnaseq_sample_metadata_242.csv",
    # TCGA/BraTS — expression data (immutable), MRI data extracted from nested zip
    "tcga_expression_file_level": "data/tcga_brain_tumor_expression/tcga_gbm_lgg_primary_tumor_tpm_unstranded_file_level.tsv",
    "tcga_expression_sample_mean": "data/tcga_brain_tumor_expression/tcga_gbm_lgg_primary_tumor_tpm_unstranded_sample_mean.tsv",
    "brats_training_dir": "data/brats_tcga_lgg_training_65/",
    # External benchmarks
    "huang2025_cfRNA": "external_inputs/huang2025_pmc12041490/41698_2025_909_MOESM2_ESM.csv",
    # NOTE: braintrace_source_tracing.db is a BUILD ARTIFACT (Step 1: atlas_database),
    # NOT a raw data source. It is regenerated from the above sources.
}


# ── Main pipeline ────────────────────────────────────────────────────────────


def verify_raw_data() -> dict[str, str]:
    """Verify SHA256 of all raw data sources against SHA256SUMS.txt."""
    print("=" * 70)
    print("STEP 0: Verifying raw data integrity (SHA256) ...")
    print("=" * 70)

    # Parse SHA256SUMS
    expected: dict[str, str] = {}
    if SHA256SUMS.exists():
        with open(SHA256SUMS) as f:
            for line in f:
                line = line.strip()
                if not line or line.startswith("#"):
                    continue
                parts = line.split()
                if len(parts) >= 2:
                    expected[parts[-1]] = parts[0]

    results: dict[str, str] = {}
    all_pass = True

    for label, rel_path in RAW_DATA_SOURCES.items():
        full_path = ROOT / rel_path
        if not full_path.exists():
            status = "MISSING"
            all_pass = False
        else:
            actual = sha256_file(full_path)
            if rel_path in expected:
                if actual == expected[rel_path]:
                    status = "OK"
                else:
                    status = f"HASH_MISMATCH (expected {expected[rel_path][:12]}..., got {actual[:12]}...)"
                    all_pass = False
            else:
                status = f"NOT_IN_MANIFEST (hash={actual[:12]}...)"
        results[label] = status
        icon = " PASS " if status == "OK" else " FAIL " if status != "NOT_IN_MANIFEST" else " WARN "
        print(f"  [{icon}] {label}: {rel_path} — {status}")

    if not all_pass:
        print("\n  WARNING: Some raw data files failed verification.")
        print("  Results may not be reproducible until issues are resolved.")
    else:
        print("\n  All raw data files verified successfully.")

    return results


def capture_environment() -> dict:
    """Capture Python environment for reproducibility."""
    result = subprocess.run(
        [sys.executable, "-m", "pip", "freeze"],
        capture_output=True,
        text=True,
        timeout=30,
    )
    packages = {}
    for line in result.stdout.strip().split("\n"):
        if "==" in line:
            pkg, ver = line.split("==", 1)
            packages[pkg] = ver

    return {
        "python_version": sys.version,
        "platform": platform.platform(),
        "hostname": platform.node(),
        "packages": packages,
    }


def execute_pipeline(
    steps: list[BuildStep],
    phase: str,
    skip_build: bool = False,
) -> list[AuditRecord]:
    """Execute a list of build/validation steps."""
    records: list[AuditRecord] = []
    total = len(steps)
    passed = 0
    failed = 0
    skipped = 0

    for i, step in enumerate(steps, 1):
        print(f"\n{'─' * 70}")
        print(f"STEP {phase}.{i}/{total}: {step.name}")
        print(f"  Description: {step.description}")

        if skip_build and phase == "BUILD":
            print("  [SKIP] --skip-build flag set, using pre-built assets")
            records.append(
                AuditRecord(step=step.name, status="SKIP", duration_sec=0.0, notes="--skip-build")
            )
            skipped += 1
            continue

        # Verify dependencies
        missing_deps = []
        for dep in step.depends_on:
            if not (ROOT / dep).exists():
                missing_deps.append(dep)

        if missing_deps:
            print(f"  [SKIP] Missing dependencies: {', '.join(missing_deps)}")
            records.append(
                AuditRecord(
                    step=step.name,
                    status="SKIP",
                    duration_sec=0.0,
                    notes=f"Missing deps: {missing_deps}",
                )
            )
            skipped += 1
            continue

        # Verify input checksums
        input_checksums = {}
        for dep in step.depends_on:
            dep_path = ROOT / dep
            if dep_path.is_file():
                input_checksums[dep] = sha256_file(dep_path)
            elif dep_path.is_dir():
                input_checksums[dep] = "DIRECTORY"

        # Set seed environment
        extra_env = {}
        if step.seed and step.seed in SEED_REGISTRY:
            extra_env["BRAINTRACE_SEED"] = str(SEED_REGISTRY[step.seed])

        # Run step
        extra_args = list(step.extra_args)
        if step.seed and step.seed in SEED_REGISTRY and "--seed" in " ".join(sys.argv):
            extra_args.extend(["--seed", str(SEED_REGISTRY[step.seed])])

        rc, output, elapsed = run_step(step.script, extra_args, env=extra_env)

        # Verify outputs
        output_checksums = {}
        all_outputs_exist = True
        for out_rel in step.produces:
            out_path = ROOT / out_rel
            if out_path.is_file():
                output_checksums[out_rel] = sha256_file(out_path)
            elif out_path.is_dir() and any(out_path.iterdir()):
                output_checksums[out_rel] = "DIRECTORY_EXISTS"
            else:
                all_outputs_exist = False
                output_checksums[out_rel] = "MISSING"

        if rc == 0 and all_outputs_exist:
            status = "PASS"
            passed += 1
            icon = " PASS "
        elif rc != 0:
            status = "FAIL"
            failed += 1
            icon = " FAIL "
        else:
            status = "WARN"
            failed += 1
            icon = " WARN "

        record = AuditRecord(
            step=step.name,
            status=status,
            duration_sec=elapsed,
            output_checksums=output_checksums,
            input_checksums=input_checksums,
            notes=f"Exit code: {rc}" if rc != 0 else "",
        )
        records.append(record)

        print(f"  [{icon}] {status} ({elapsed:.1f}s)")

        # Show abbreviated output on failure
        if rc != 0:
            print(f"  --- STDERR tail ---")
            err_lines = output.split("\n")
            for line in err_lines[-10:]:
                if line.strip():
                    print(f"    {line[:120]}")

    print(f"\n  Phase {phase} summary: {passed} passed, {failed} failed, {skipped} skipped")
    return records


def generate_report(
    raw_data_results: dict,
    build_records: list[AuditRecord],
    validation_records: list[AuditRecord],
    env_info: dict,
) -> AuditReport:
    """Generate the complete audit report."""
    report = AuditReport(
        generated_at=datetime.now(timezone.utc).isoformat(),
        hostname=env_info["hostname"],
        platform=env_info["platform"],
        python_version=env_info["python_version"],
        pip_freeze=env_info["packages"],
        seed_registry=SEED_REGISTRY,
        raw_data_verification=raw_data_results,
        build_steps=build_records,
        validation_steps=validation_records,
    )

    # Collect final output checksums
    for step_list in [build_records, validation_records]:
        for record in step_list:
            for path, checksum in record.output_checksums.items():
                if checksum not in ("MISSING", "DIRECTORY_EXISTS", "DIRECTORY"):
                    report.final_output_checksums[path] = checksum

    # Write JSON report
    report_path = REPRO_DIR / "reproducibility_audit.json"
    with open(report_path, "w", encoding="utf-8") as f:
        json.dump(report, f, indent=2, ensure_ascii=False, default=str)
    print(f"\n  Audit report written to: {report_path}")

    # Write human-readable summary
    summary_path = REPRO_DIR / "reproducibility_summary.txt"
    with open(summary_path, "w", encoding="utf-8") as f:
        f.write("=" * 70 + "\n")
        f.write("BrainTrace — Reproducibility Audit Summary\n")
        f.write(f"Generated: {report.generated_at}\n")
        f.write(f"Platform: {report.platform}\n")
        f.write(f"Python: {report.python_version}\n")
        f.write("=" * 70 + "\n\n")

        f.write("RAW DATA VERIFICATION\n")
        f.write("-" * 40 + "\n")
        for label, status in raw_data_results.items():
            f.write(f"  {label}: {status}\n")

        for phase_name, records in [("BUILD", build_records), ("VALIDATION", validation_records)]:
            f.write(f"\n{phase_name} STEPS\n")
            f.write("-" * 40 + "\n")
            for r in records:
                f.write(f"  {r.step}: {r.status} ({r.duration_sec:.1f}s)\n")
                if r.notes:
                    f.write(f"    Notes: {r.notes}\n")

        f.write(f"\nSEED REGISTRY\n")
        f.write("-" * 40 + "\n")
        for name, seed in SEED_REGISTRY.items():
            f.write(f"  {name}: {seed}\n")

        f.write(f"\nFINAL OUTPUT CHECKSUMS ({len(report.final_output_checksums)} files)\n")
        f.write("-" * 40 + "\n")
        for path, checksum in sorted(report.final_output_checksums.items()):
            f.write(f"  {checksum}  {path}\n")

    print(f"  Summary written to: {summary_path}")
    return report


def main() -> int:
    parser = argparse.ArgumentParser(
        description="BrainTrace Master Reproducibility Pipeline",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  python reproduce_all.py                          # Run everything
  python reproduce_all.py --verify-only            # Only verify raw data
  python reproduce_all.py --skip-build             # Skip asset building (use pre-built)
  python reproduce_all.py --step network_model     # Run a single step
        """,
    )
    parser.add_argument("--verify-only", action="store_true", help="Only verify raw data SHA256")
    parser.add_argument("--skip-build", action="store_true", help="Skip model/DB build steps")
    parser.add_argument("--step", type=str, help="Run a single named step")
    parser.add_argument("--output-dir", type=Path, default=REPRO_DIR)
    args = parser.parse_args()

    # Capture environment
    print("=" * 70)
    print("BrainTrace — Reproducibility Pipeline")
    print(f"  Python: {sys.version}")
    print(f"  Platform: {platform.platform()}")
    print(f"  Root: {ROOT}")
    print(f"  Audit dir: {args.output_dir}")
    print("=" * 70)

    env_info = capture_environment()
    print(f"\n  Found {len(env_info['packages'])} installed Python packages.")

    # Step 0: Verify raw data
    raw_results = verify_raw_data()

    if args.verify_only:
        print("\n  --verify-only mode: skipping build and validation steps.")
        return 0

    # ── Pre-build: Extract nested archives ─────────────────────────────────
    print("\n" + "=" * 70)
    print("PRE-BUILD: Extracting nested archives ...")
    print("=" * 70)

    brats_ok = True
    if not args.skip_build:
        print("\n  [BraTS-TCGA-LGG NIfTI extraction]")
        brats_ok = extract_brats_nested_zip()
        if not brats_ok:
            print("  WARNING: BraTS extraction failed. TCGA/BraTS validation may be skipped.")
    else:
        print("  [SKIP] --skip-build flag set, assuming data is already extracted")

    # ── Build assets ──────────────────────────────────────────────────────
    if args.step:
        # Run a single step
        all_steps = {s.name: s for s in BUILD_STEPS + VALIDATION_STEPS}
        if args.step not in all_steps:
            print(f"Unknown step: {args.step}")
            print(f"Available: {sorted(all_steps)}")
            return 1
        target = all_steps[args.step]
        phase_steps = [s for s in BUILD_STEPS if s.name == args.step] or [
            s for s in VALIDATION_STEPS if s.name == args.step
        ]
        build_records = execute_pipeline(
            phase_steps if phase_steps[0] in BUILD_STEPS else [], "BUILD", args.skip_build
        )
        validation_records = execute_pipeline(
            phase_steps if phase_steps[0] in VALIDATION_STEPS else [], "VALIDATION"
        )
    else:
        # Full pipeline
        build_records = execute_pipeline(BUILD_STEPS, "BUILD", args.skip_build)
        validation_records = execute_pipeline(VALIDATION_STEPS, "VALIDATION")

    # Generate report
    report = generate_report(raw_results, build_records, validation_records, env_info)

    # Final summary
    build_pass = sum(1 for r in build_records if r.status == "PASS")
    build_total = len(build_records)
    val_pass = sum(1 for r in validation_records if r.status == "PASS")
    val_total = len(validation_records)

    print(f"\n{'=' * 70}")
    print(f"PIPELINE COMPLETE")
    print(f"  Build:     {build_pass}/{build_total} passed")
    print(f"  Validation: {val_pass}/{val_total} passed")
    print(f"  Audit report: {args.output_dir / 'reproducibility_audit.json'}")
    print(f"  Human summary: {args.output_dir / 'reproducibility_summary.txt'}")
    print(f"{'=' * 70}")

    return 0 if (build_pass == build_total and val_pass == val_total) else 1


if __name__ == "__main__":
    sys.exit(main())
