[server]
headless = true
enableCORS = false
enableXsrfProtection = false
maxUploadSize = 1024

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#1f77b4"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F5F7FA"
textColor = "#262730"
